### ISSUE TITLE
Fails to launch ray.so; almost certainly a skill issue

### ISSUE THREAD

**Issue by nexxai** [TobinPalmer/rayso.nvim#7]
Hey there, I'm super excited to try this plugin but having some issues getting it to work and hoping someone out there can assist me.

`lua/plugins/rayso.lua`
```lua
return {
  "TobinPalmer/rayso.nvim",
  cmd = { "Rayso" },
  config = function()
    require("rayso").setup({
      open_cmd = "Arc",
      base_url = "https://ray.so/",
      options = {
        background = true,
        dark_mode = true,
        theme = "breeze",
        logging_enabled = true,
        logging_path = "/Users/nexxai/Documents/Rayso/",
        logging_file = "rayso.md",
        title = "nexxai",
        padding = 32,
      },
    })
  end,
}
```

If I enter visual mode, select some text and do `:Rayso`, I get this error message:
<img width="1368" alt="Screenshot 2024-02-29 at 2 27 39 PM" src="https://github.com/TobinPalmer/rayso.nvim/assets/4316564/818fd30d-856d-414a-bf22-6595e5d9b76e">

Can anyone see what I'm doing wrong here?

**Comment by TobinPalmer** [comment]
Has it been fixed sorry i'm late

**Comment by nexxai** [comment]
No, it's still broken as far as I can tell

**Comment by TobinPalmer** [comment]
Ok, I belive I fixed this, but one issue with your config is the .md in the logging_file. it can only be md so just put `rayso`.

**Comment by nexxai** [comment]
@TobinPalmer It works perfectly!  Thank you!!!
