### ISSUE TITLE
Unintended emphasized lines

### ISSUE THREAD

**Issue by SunghoLee** [TobinPalmer/rayso.nvim#8]
Dear all,

I just have started to configure and use this. Most things are excellent, but the generated image automatically emphasizes the first three lines of code. It's not the behavior I want. How can I configure this to remove the emphasis? I'm trying this on the M1 Macbook Pro.

![image](https://github.com/TobinPalmer/rayso.nvim/assets/5790819/df612b11-fea5-4360-b07e-c513ba0b1573)

**Comment by TobinPalmer** [comment]
I tried the exact same config and didn't get any emphasis on any lines. Are you viewing the code from the ray.so website?

**Comment by SunghoLee** [comment]
Oops, it was the problem with my Mac since the problem disappeared after rebooting the Mac.
Sorry for the silly issue.
